# Generated by Django 2.1.1 on 2018-09-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.PositiveIntegerField(unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('indetificador', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo_recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque_tecnologico.TipoRecurso'),
        ),
    ]
