# Generated by Django 2.1.1 on 2018-10-06 14:50

from django.db import migrations
from django.utils import timezone


def migrateDB(apps, schema_editor):
    recursos = apps.get_model("parque_tecnologico", "Recurso").objects.all()
    for recurso in recursos:
        recurso.ultima_actualizacion = timezone.now()
        recurso.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parque_tecnologico', '0002_recurso_ultima_actualizacion'),
    ]

    operations = [
        migrations.RunPython(migrateDB)
    ]

