# Generated by Django 2.1.1 on 2018-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque_tecnologico', '0003_auto_20181006_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
